### ISSUE TITLE
Should `Corpus.documents` return `Document` objects?

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.api#29]
As the idea of the package is to use PyPLN in a pythonic way, maybe the best thing to do with `documents` attribute on `Corpus` object is to return a list of `Document` objects. I don't know if this would impact in performance, since:
-  A `Corpus` could have a **huge** number of documents and a little string with document URL is way lighter than a `Document` object; and
- The method `Document.from_url` requires one request being made to create the object from the URL.

A possible approach would be creating a `LazyDocument` class, that stores only its URL and in the first time the user tries to access one attribute it does the request as `Document.from_url` does (this class should have the same methods and attributes as `Document`).

**Comment by fccoelho** [comment]
I think that the main issue here is not if we should return all the documents. But what is the most efficient way to do it. And for that we must at all costs avoid making a separate request for each document.

I am closing this issue so that we can handle the fetching of large sets of documents efficiently.
